- name: GitLab | Get Job Information
  uri:
    url: "{{ GITLAB_URL }}/api/v4/projects/{{ GITLAB_PROJECT | regex_replace('/', '%2F') }}/pipelines/{{ GITLAB_PIPELINE }}/jobs"
    headers:
      PRIVATE-TOKEN: "{{ GITLAB_TOKEN }}"
  register: GITLAB_BUILD

- name: GitLab | Create Temporary Folder For Artifacts
  tempfile:
    state: directory
    suffix: artifacts
  register: GITLAB_TEMP_DIR

- name: GitLab | Download Artifacts
  get_url:
    url: "{{ GITLAB_URL }}/api/v4/projects/{{ GITLAB_PROJECT | regex_replace('/', '%2F') }}/jobs/artifacts/{{ GITLAB_BUILD.json[0].ref }}/download?job=build"
    headers: 'PRIVATE-TOKEN: {{ GITLAB_TOKEN }}'
    dest: "{{ GITLAB_TEMP_DIR.path }}/{{ GITLAB_PIPELINE }}.zip"

- name: GitLab | Extract Artifacts
  unarchive:
    remote_src: yes
    src: "{{ GITLAB_TEMP_DIR.path }}/{{ GITLAB_PIPELINE }}.zip"
    dest: "{{ GITLAB_UNARCHIVE_PATH }}"

- name: GitLab | Delete Temporary Folder
  file:
    dest: "{{ GITLAB_TEMP_DIR.path }}"
    state: absent